name: Build and Publish ZippedImageApi

on:
  push:
    branches:
      - master
    paths:
      - 'ZippedImageApi/**'
      - '.github/workflows/publish-zippedimageapi.yml'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ZippedImageApi/ZippedImageApi.csproj

      - name: Build
        run: dotnet build ZippedImageApi/ZippedImageApi.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ZippedImageApi/ZippedImageApi.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
